# Generated by Django 5.2.9 on 2025-12-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='role',
            field=models.CharField(choices=[('std', 'Student'), ('teach', 'Teacher')], default='role', max_length=5),
            preserve_default=False,
        ),
    ]
